### ISSUE TITLE
RangeError exception thrown when connecting without timeout on 32bit machine

### ISSUE THREAD

**Issue by ollej** [busyloop/net-ssh-simple#8]
I'm experiencing an error when trying to connect on a 32bit machine with the latest net-ssh-simple. It seems that the new 32bit check doesn't work properly with my setup.

### Possibly relevant information
Debian 7.10
Linux 3.2.0-4-686-pae (32bit)
Ruby v2.3.3
Net-ssh-simple v1.7.0
Net-ssh v4.1.0

### Example of error

```
irb(main):001:0> require 'socket'; Socket.tcp('127.0.0.1', 1, connect_timeout: 2**32).close
RangeError: bignum too big to convert into `long'
	from /home/promote/.rbenv/versions/2.3.3/lib/ruby/2.3.0/socket.rb:60:in `wait_writable'
	from /home/promote/.rbenv/versions/2.3.3/lib/ruby/2.3.0/socket.rb:60:in `connect_internal'
	from /home/promote/.rbenv/versions/2.3.3/lib/ruby/2.3.0/socket.rb:139:in `connect'
	from /home/promote/.rbenv/versions/2.3.3/lib/ruby/2.3.0/socket.rb:636:in `block in tcp'
	from /home/promote/.rbenv/versions/2.3.3/lib/ruby/2.3.0/socket.rb:231:in `each'
	from /home/promote/.rbenv/versions/2.3.3/lib/ruby/2.3.0/socket.rb:231:in `foreach'
	from /home/promote/.rbenv/versions/2.3.3/lib/ruby/2.3.0/socket.rb:626:in `tcp'
	from (irb):1
	from /home/promote/.rbenv/versions/2.3.3/bin/irb:11:in `<main>'
```

### Naive solution

I solved it temporarily with this fix, but it doesn't quite seem like the right solution to me.

```
diff --git a/lib/net/ssh/simple.rb b/lib/net/ssh/simple.rb
index f9263e6..42dca56 100755
--- a/lib/net/ssh/simple.rb
+++ b/lib/net/ssh/simple.rb
@@ -602,7 +602,7 @@ module Net
       is_64bit_platform = true
       begin
         Socket.tcp('127.0.0.1', 1, connect_timeout: 2**32).close
-      rescue Errno::EINVAL
+      rescue Errno::EINVAL, RangeError
         is_64bit_platform = false
       rescue
       end
```

**Comment by m-o-e** [comment]
Thanks for the report!

The 32bit check is indeed not well tested and should probably be
changed to a different approach in the future (not yet sure which, though).

For now I have merged your workaround, as it seems to
resolve the issue and I can't think of any negative side-effects.
